name: weread data sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  sync:
    name: Sync WeRead Data
    runs-on: ubuntu-latest
    env:
      WEREAD_COOKIE: ${{ secrets.WEREAD_COOKIE }}
      GITHUB_REPO: GladiousZhang/gladiouszhang.github.io
      GITHUB_BRANCH: main
      DATA_DIR: data
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Fetch WeRead data and save as JSON
        run: |
          python scripts/weread.py
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.GITHUB_REPO }}
          ref: ${{ env.GITHUB_BRANCH }}
          path: target-repo
          token: ${{ env.GITHUB_TOKEN }}
      - name: Move JSON file to target repository
        run: |
          mkdir -p target-repo/${{ env.DATA_DIR }}
          mv weread_books.json target-repo/${{ env.DATA_DIR }}/books.json
      - name: Commit and push changes to target repository
        working-directory: target-repo
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ${{ env.DATA_DIR }}/books.json
          git commit -m 'Update WeRead data in books.json' || echo "nothing to commit"
          git push || echo "nothing to push"
